//   PHY address space allocation
//   Description: PHY uses 22-bit address encoding, corresponding to AHB bus address [21:0]
//
//   |--------------|---------|-----------------------
//   | Address Space       |Size         |Address Range
//   |--------------|---------|-----------------------
//   | ITIM Sram    |64K      |0x0000_0000-0x0000_FFFF
//   | DTIM Sram    |32K      |0x0001_0000-0x0001_7FFF
//   | FPTIM Sram   |128K     |0x0002_0000-0x0003_FFFF
//   | MTTIM Sram   |8K       |0x0004_0000-0x0004_1FFF
//   | McuCsr       |8K       |0x0005_0000-0x0005_1FFF
//   | CRBus        |2048K    |0x0020_0000-0x003F_FFFF
//   |--------------|---------|-----------------------

//   CR bus address field division
//   |--------|---------------------|--------------------------------
//   |Bits    |Filed                |Descripition
//   |--------|---------------------|--------------------------------
//   |19      |                     |0:MCU (Sram+McuCsr)
//   |        |                     |1:CRBus"
//   |--------|---------------------|--------------------------------
//   |18:15   |filed type           |0x0~9:DB
//   |        |                     |0xa:CA0
//   |        |                     |0xb:CA1
//   |        |                     |0xc:TOP
//   |        |                     |0xe:DB broadcast
//   |        |                     |0xf:CA broadcast"
//   |--------|---------------------|--------------------------------
//   |14:12   |Pstate type          |3'b000~3'b001:Pstate unrelate
//   |        |                     |3'b011:Pstate broadcast
//   |        |                     |3'b100:Pstate0
//   |        |                     |3'b101:Pstate1
//   |        |                     |3'b110:Pstate2
//   |        |                     |3'b111:Pstate3
//   |--------|---------------------|--------------------------------
//   |11:00   |register difine      |each register define
//   |--------|---------------------|--------------------------------



// Base address naming (32-bit aligned, corresponding AHB bus address needs *4)
#define ITIM_BASE                           (0x00000)
#define DTIM_BASE                           (0x04000)
#define DTIM_SIZE                           (0x2000)   //32K
#define FPTIM_BASE                          (0x8000)
#define MTTIM_BASE                          (0x10000)
#define MCUCSR_BASE                         (0x14000)
#define DB_BASE(n)                          (0x80000 + 0x8000 * n)
#define CA_BASE(n)                          (0xd0000 + 0x8000 * n)
#define AKS_PHY_TOP_BASE                            (0xe0000)
#define DQ_BASE(n, l)                       (DB_BASE(n) + 0x1000 + 0x100 * l)
#define DQS_BASE(n, l)                      (DB_BASE(n) + 0x1900 + 0x100 * l)
#define CA_OUT_BASE(n, l)                   (CA_BASE(n) + 0x1000 + 0x40 * l)
#define CA_CK_BASE(n, l)                    (CA_BASE(n) + 0x1c00 + 0x40 * l)

#define PSTATE_BASE(p)                      (0x4000 + 0x1000 * p)

#define MESSAGE_LOCAL                       (DTIM_BASE + DTIM_SIZE - 256)   //()

/* ---------------------------- aks_addrphy_top_slv ------------------------------*/
#define     RESET_CONFIG                                    (AKS_PHY_TOP_BASE + 0x0)
#define     PHY_WORK_MODE                                   (AKS_PHY_TOP_BASE + 0x1)
#define     CLK_GATE_CFG                                    (AKS_PHY_TOP_BASE + 0x2)
#define     TEST_ENABLE                                     (AKS_PHY_TOP_BASE + 0x3)
#define     POR_CONFIG                                      (AKS_PHY_TOP_BASE + 0x4)
#define     PLL_BASIC_CONFIG                                (AKS_PHY_TOP_BASE + 0x5)
#define     PLL_PINT_CONFIG                                 (AKS_PHY_TOP_BASE + 0x6)
#define     PLL_MODE_CONFIG                                 (AKS_PHY_TOP_BASE + 0x7)
#define     ALERT_CH0_IO_TEST_STA                           (AKS_PHY_TOP_BASE + 0x8)
#define     ALERT_CH1_IO_TEST_STA                           (AKS_PHY_TOP_BASE + 0x9)
#define     ALERT_CH0_ZQCAL_CONFIG                          (AKS_PHY_TOP_BASE + 0xa)
#define     ALERT_CH0_MODE_CONFIG                           (AKS_PHY_TOP_BASE + 0xb)
#define     ALERT_CH0_ODT_CONFIG                            (AKS_PHY_TOP_BASE + 0xc)
#define     ALERT_CH0_DFE_CONFIG                            (AKS_PHY_TOP_BASE + 0xd)
#define     ALERT_CH0_VDD_MODE_CONFIG                       (AKS_PHY_TOP_BASE + 0xe)
#define     ALERT_CH0_DAC_CONFIG                            (AKS_PHY_TOP_BASE + 0xf)
#define     ALERT_CH0_TXFFE_CONFIG                          (AKS_PHY_TOP_BASE + 0x10)
#define     ALERT_CH1_ZQCAL_CONFIG                          (AKS_PHY_TOP_BASE + 0x11)
#define     ALERT_CH1_MODE_CONFIG                           (AKS_PHY_TOP_BASE + 0x12)
#define     ALERT_CH1_ODT_CONFIG                            (AKS_PHY_TOP_BASE + 0x13)
#define     ALERT_CH1_DFE_CONFIG                            (AKS_PHY_TOP_BASE + 0x14)
#define     ALERT_CH1_VDD_MODE_CONFIG                       (AKS_PHY_TOP_BASE + 0x15)
#define     ALERT_CH1_DAC_CONFIG                            (AKS_PHY_TOP_BASE + 0x16)
#define     ALERT_CH1_TXFFE_CONFIG                          (AKS_PHY_TOP_BASE + 0x17)
#define     ALERT_BASIC_CONFIG                              (AKS_PHY_TOP_BASE + 0x18)
#define     PLL_STATE                                       (AKS_PHY_TOP_BASE + 0x19)
#define     PLL_RESERVED                                    (AKS_PHY_TOP_BASE + 0x1a)
#define     LOWER_SPEED_1UI_NUM_CFG                         (AKS_PHY_TOP_BASE + 0x1b)
#define     PLL_TX_CLK_GATE                                 (AKS_PHY_TOP_BASE + 0x1c)
#define     TRAINING_CLK_GATE                               (AKS_PHY_TOP_BASE + 0x20)
#define     ZQ_MODE_CONFIG                                  (AKS_PHY_TOP_BASE + 0x21)
#define     ZQ_SLICE_CONFIG                                 (AKS_PHY_TOP_BASE + 0x22)
#define     GLB_VREF_CONFIG                                 (AKS_PHY_TOP_BASE + 0x23)
#define     PHY_MACRO_DEFINE                                (AKS_PHY_TOP_BASE + 0x24)
#define     MEMRESET_CONFIG                                 (AKS_PHY_TOP_BASE + 0x27)
#define     MEMRESET_TX_CONFIG                              (AKS_PHY_TOP_BASE + 0x28)
#define     MEMRESET_BYPASS_CONFIG                          (AKS_PHY_TOP_BASE + 0x29)
#define     REAL_RATIO_CFG                                  (AKS_PHY_TOP_BASE + 0x40)
#define     DFI_INTF_ENABLE                                 (AKS_PHY_TOP_BASE + 0x41)
#define     FPSTATE_SEL                                     (AKS_PHY_TOP_BASE + 0x42)
#define     CUR_FREQ_INFO                                   (AKS_PHY_TOP_BASE + 0x43)
#define     PCU_TEST_EN                                     (AKS_PHY_TOP_BASE + 0x44)
#define     DSM_CFG                                         (AKS_PHY_TOP_BASE + 0x45)
#define     CFG_INTF_SEL                                    (AKS_PHY_TOP_BASE + 0x46)
#define     INIT_OPT_EN                                     (AKS_PHY_TOP_BASE + 0x48)
#define     INIT_FSM_STATUS                                 (AKS_PHY_TOP_BASE + 0x49)
#define     INIT_ERROR_INFO                                 (AKS_PHY_TOP_BASE + 0x4a)
#define     PHYMASTER_OPT_EN                                (AKS_PHY_TOP_BASE + 0x4b)
#define     PHYMASTER_INTERVAL                              (AKS_PHY_TOP_BASE + 0x4c)
#define     PHYMASTER_CFG                                   (AKS_PHY_TOP_BASE + 0x4d)
#define     PHYMASTER_MASK_UPD                              (AKS_PHY_TOP_BASE + 0x4e)
#define     PHYMASTER_FSM_STATUS                            (AKS_PHY_TOP_BASE + 0x4f)
#define     PHYMASTER_ERROR_INFO                            (AKS_PHY_TOP_BASE + 0x50)
#define     UPDATE_OPT_EN                                   (AKS_PHY_TOP_BASE + 0x51)
#define     PHYUPD_INTERVAL                                 (AKS_PHY_TOP_BASE + 0x52)
#define     PHYUPD_CFG                                      (AKS_PHY_TOP_BASE + 0x53)
#define     UPDATE_FSM_STATUS                               (AKS_PHY_TOP_BASE + 0x54)
#define     UPDATE_ERROR_INFO                               (AKS_PHY_TOP_BASE + 0x55)
#define     DFI_SIDEBAND_EN                                 (AKS_PHY_TOP_BASE + 0x56)

#define     PCLK_PTR_INIT                                   (AKS_PHY_TOP_BASE + 0x58)
#define     SOFT_OPT_EN                                     (AKS_PHY_TOP_BASE + 0x59)
#define     DFI_LP_EN                                       (AKS_PHY_TOP_BASE + 0x5a)
#define     REAL_TIMER_RUN_EN                               (AKS_PHY_TOP_BASE + 0x5b)
#define     DMA_CTRL                                        (AKS_PHY_TOP_BASE + 0x5c)
#define     DMA_SRC_ADDR                                    (AKS_PHY_TOP_BASE + 0x5d)
#define     DMA_DST_ADDR                                    (AKS_PHY_TOP_BASE + 0x5e)
#define     DMA_XFER_LEN_CFG1                               (AKS_PHY_TOP_BASE + 0x5f)
#define     DMA_CLK_GATE                                    (AKS_PHY_TOP_BASE + 0x61)
#define     ZQ_CAL_TIMEOUT_POINT                            (AKS_PHY_TOP_BASE + 0x70)
#define     DDL_CAL_TIMEOUT_POINT                           (AKS_PHY_TOP_BASE + 0x71)
#define     RETRAIN_TIMEOUT_POINT                           (AKS_PHY_TOP_BASE + 0x72)
#define     PLL_TIMEOUT_POINT                               (AKS_PHY_TOP_BASE + 0x73)
#define     MTFSM_TIMEOUT_POINT                             (AKS_PHY_TOP_BASE + 0x74)
#define     DMA_TIMEOUT_POINT                               (AKS_PHY_TOP_BASE + 0x75)

#define     FPSTATE_REMAP_CFG0                              (AKS_PHY_TOP_BASE + 0x76)
#define     FPSTATE_REMAP_CFG1                              (AKS_PHY_TOP_BASE + 0x77)
#define     FPSTATE_REMAP_CFG2                              (AKS_PHY_TOP_BASE + 0x78)
#define     FPSTATE_REMAP_CFG3                              (AKS_PHY_TOP_BASE + 0x79)

#define     DRAM_FSP_PHY_FPSTATE                            (AKS_PHY_TOP_BASE + 0x7a)
#define     FPSTATE_FREQ_INFO_0                             (AKS_PHY_TOP_BASE + 0x7b)
#define     FPSTATE_FREQ_INFO_1                             (AKS_PHY_TOP_BASE + 0x7c)
#define     FPSTATE_FREQ_INFO_2                             (AKS_PHY_TOP_BASE + 0x7e)
#define     FPSTATE_FREQ_INFO_3                             (AKS_PHY_TOP_BASE + 0x7e)

#define     PROFRAM_CONFG_EN                                (AKS_PHY_TOP_BASE + 0x7f)
#define     PROFRAM_CONFG_ADDR00                            (AKS_PHY_TOP_BASE + 0x80)
#define     PROFRAM_CONFG_ADDR01                            (AKS_PHY_TOP_BASE + 0x81)
#define     PROFRAM_CONFG_ADDR02                            (AKS_PHY_TOP_BASE + 0x82)
#define     PROFRAM_CONFG_ADDR03                            (AKS_PHY_TOP_BASE + 0x83)
#define     PROFRAM_CONFG_ADDR04                            (AKS_PHY_TOP_BASE + 0x84)
#define     PROFRAM_CONFG_ADDR05                            (AKS_PHY_TOP_BASE + 0x85)
#define     PROFRAM_CONFG_ADDR06                            (AKS_PHY_TOP_BASE + 0x86)
#define     PROFRAM_CONFG_ADDR07                            (AKS_PHY_TOP_BASE + 0x87)
#define     PROFRAM_CONFG_ADDR08                            (AKS_PHY_TOP_BASE + 0x88)
#define     PROFRAM_CONFG_ADDR09                            (AKS_PHY_TOP_BASE + 0x89)
#define     PROFRAM_CONFG_ADDR0A                            (AKS_PHY_TOP_BASE + 0x8a)
#define     PROFRAM_CONFG_ADDR0B                            (AKS_PHY_TOP_BASE + 0x8b)
#define     PROFRAM_CONFG_ADDR0C                            (AKS_PHY_TOP_BASE + 0x8c)
#define     PROFRAM_CONFG_ADDR0D                            (AKS_PHY_TOP_BASE + 0x8d)
#define     PROFRAM_CONFG_ADDR0E                            (AKS_PHY_TOP_BASE + 0x8e)
#define     PROFRAM_CONFG_ADDR0F                            (AKS_PHY_TOP_BASE + 0x8f)
#define     PROFRAM_CONFG_DATA00                            (AKS_PHY_TOP_BASE + 0x90)
#define     PROFRAM_CONFG_DATA01                            (AKS_PHY_TOP_BASE + 0x91)
#define     PROFRAM_CONFG_DATA02                            (AKS_PHY_TOP_BASE + 0x92)
#define     PROFRAM_CONFG_DATA03                            (AKS_PHY_TOP_BASE + 0x93)
#define     PROFRAM_CONFG_DATA04                            (AKS_PHY_TOP_BASE + 0x94)
#define     PROFRAM_CONFG_DATA05                            (AKS_PHY_TOP_BASE + 0x95)
#define     PROFRAM_CONFG_DATA06                            (AKS_PHY_TOP_BASE + 0x96)
#define     PROFRAM_CONFG_DATA07                            (AKS_PHY_TOP_BASE + 0x97)
#define     PROFRAM_CONFG_DATA08                            (AKS_PHY_TOP_BASE + 0x98)
#define     PROFRAM_CONFG_DATA09                            (AKS_PHY_TOP_BASE + 0x99)
#define     PROFRAM_CONFG_DATA0A                            (AKS_PHY_TOP_BASE + 0x9a)
#define     PROFRAM_CONFG_DATA0B                            (AKS_PHY_TOP_BASE + 0x9b)
#define     PROFRAM_CONFG_DATA0C                            (AKS_PHY_TOP_BASE + 0x9c)
#define     PROFRAM_CONFG_DATA0D                            (AKS_PHY_TOP_BASE + 0x9d)
#define     PROFRAM_CONFG_DATA0E                            (AKS_PHY_TOP_BASE + 0x9e)
#define     PROFRAM_CONFG_DATA0F                            (AKS_PHY_TOP_BASE + 0x9f)
#define     DDR_CFG                                         (AKS_PHY_TOP_BASE + 0xa1)
#define     LOOP_CFG                                        (AKS_PHY_TOP_BASE + 0xa2)
#define     TOP_DDL_CFG                                     (AKS_PHY_TOP_BASE + 0xa3)
#define     SRC_CFG                                         (AKS_PHY_TOP_BASE + 0xa4)
#define     DB_CFG                                          (AKS_PHY_TOP_BASE + 0xa5)
#define     CA_CFG                                          (AKS_PHY_TOP_BASE + 0xa6)
#define     MONI_DL_CFG                                     (AKS_PHY_TOP_BASE + 0xb0)
#define     MONI_DL_CAL_CYC_NUM                             (AKS_PHY_TOP_BASE + 0xb1)
#define     MONI_DL_1UI_CODE_STEP_CFG                       (AKS_PHY_TOP_BASE + 0xb2)
#define     MONI_DL_CAL_INFO                                (AKS_PHY_TOP_BASE + 0xb3)
#define     MONI_DL_CAL_ALM                                 (AKS_PHY_TOP_BASE + 0xb4)
#define     ZQ_CAL_INTERVAL_CFG                             (AKS_PHY_TOP_BASE + 0xbF)
#define     ZQ_CAL_CTRL_CFG                                 (AKS_PHY_TOP_BASE + 0xc0)
#define     ZQ_CAL_CODE_STEP                                (AKS_PHY_TOP_BASE + 0xc1)
#define     ZQ_CAL_FAR_END                                  (AKS_PHY_TOP_BASE + 0xc2)
#define     ZQ_CAL_ALM                                      (AKS_PHY_TOP_BASE + 0xc3)
#define     ZQ_CAL_CODE                                     (AKS_PHY_TOP_BASE + 0xc4)
#define     RTGC_ALM                                        (AKS_PHY_TOP_BASE + 0xc5)
#define     RTGC_STRAT_PULSE                                (AKS_PHY_TOP_BASE + 0xc6)
#define     ZQ_CAL_FIRMARE_CFG                              (AKS_PHY_TOP_BASE + 0xc7)
#define     DQS_OSC_CK_CYC                                  (AKS_PHY_TOP_BASE + 0xc8)

#define     RETRAIN_ITEM_EN0                                (AKS_PHY_TOP_BASE + 0x101)
#define     ZQ_ANA_LATENCY                                  (AKS_PHY_TOP_BASE + 0x105)
#define     ZQ_CAL_OFFSET_VALUE                             (AKS_PHY_TOP_BASE + 0x106)


// MTFSM  Reg  start
#define     MTFSM_RUN_CTRL                                  (AKS_PHY_TOP_BASE + 0x200)
#define     MTFSM_RUN_STA                                   (AKS_PHY_TOP_BASE + 0x201)
#define     MTFSM_INDX_CTRL                                 (AKS_PHY_TOP_BASE + 0x202)
#define     MTFSM_INDX_STA                                  (AKS_PHY_TOP_BASE + 0x203)
#define     MTFSM_CMD_LOOP_CTRL                             (AKS_PHY_TOP_BASE + 0x204)
#define     MTFSM_ADRGEN_CTRL                               (AKS_PHY_TOP_BASE + 0x205)
#define     MTFSM_CKE_MODE                                  (AKS_PHY_TOP_BASE + 0x206)
#define     MTFSM_WCK_MODE                                  (AKS_PHY_TOP_BASE + 0x207)
#define     MTFSM_LOWFREQCLK_DIV                            (AKS_PHY_TOP_BASE + 0x208)
#define     MTFSM_TEST_CTRL                                 (AKS_PHY_TOP_BASE + 0x209)
#define     MTFSM_MP_CFG                                    (AKS_PHY_TOP_BASE + 0x20a)
#define     MTFSM_CLR                                       (AKS_PHY_TOP_BASE + 0x20b)
#define     MTFSM_RANK_SEL                                  (AKS_PHY_TOP_BASE + 0x20c)
#define     MTFSM_CA_DEFAULT                                (AKS_PHY_TOP_BASE + 0x20d)
#define     MTFSM_CS_DEFAULT                                (AKS_PHY_TOP_BASE + 0x20e)
#define     MTFSM_CSMAP_CTRL_0                              (AKS_PHY_TOP_BASE + 0x210)
#define     MTFSM_CSMAP_CTRL_1                              (AKS_PHY_TOP_BASE + 0x211)
#define     MTFSM_CSMAP_CTRL_2                              (AKS_PHY_TOP_BASE + 0x212)
#define     MTFSM_CSMAP_CTRL_3                              (AKS_PHY_TOP_BASE + 0x213)
#define     MTFSM_CSMAP_CTRL_4                              (AKS_PHY_TOP_BASE + 0x214)
#define     MTFSM_CSMAP_CTRL_5                              (AKS_PHY_TOP_BASE + 0x215)
#define     MTFSM_CSMAP_CTRL_6                              (AKS_PHY_TOP_BASE + 0x216)
#define     MTFSM_CSMAP_CTRL_7                              (AKS_PHY_TOP_BASE + 0x217)
#define     MTFSM_CSMAP_CTRL_8                              (AKS_PHY_TOP_BASE + 0x218)
#define     MTFSM_CSMAP_CTRL_9                              (AKS_PHY_TOP_BASE + 0x219)
#define     MTFSM_CSMAP_CTRL_10                             (AKS_PHY_TOP_BASE + 0x21a)
#define     MTFSM_CSMAP_CTRL_11                             (AKS_PHY_TOP_BASE + 0x21b)
#define     MTFSM_CSMAP_CTRL_12                             (AKS_PHY_TOP_BASE + 0x21c)
#define     MTFSM_CSMAP_CTRL_13                             (AKS_PHY_TOP_BASE + 0x21d)
#define     MTFSM_CSMAP_CTRL_14                             (AKS_PHY_TOP_BASE + 0x21e)
#define     MTFSM_CSMAP_CTRL_15                             (AKS_PHY_TOP_BASE + 0x21f)

#define     MTFSM_ODTCTRL_0                                 (AKS_PHY_TOP_BASE + 0x220)
#define     MTFSM_ODTCTRL_1                                 (AKS_PHY_TOP_BASE + 0x221)
#define     MTFSM_ODTCTRL_2                                 (AKS_PHY_TOP_BASE + 0x222)
#define     MTFSM_ODTCTRL_3                                 (AKS_PHY_TOP_BASE + 0x223)
#define     MTFSM_ODTCTRL_4                                 (AKS_PHY_TOP_BASE + 0x224)
#define     MTFSM_ODTCTRL_5                                 (AKS_PHY_TOP_BASE + 0x225)
#define     MTFSM_ODTCTRL_6                                 (AKS_PHY_TOP_BASE + 0x226)
#define     MTFSM_ODTCTRL_7                                 (AKS_PHY_TOP_BASE + 0x227)

#define     MTFSM_CS_PATN_0                                 (AKS_PHY_TOP_BASE + 0x230)
#define     MTFSM_CS_PATN_1                                 (AKS_PHY_TOP_BASE + 0x231)
#define     MTFSM_CS_PATN_2                                 (AKS_PHY_TOP_BASE + 0x232)
#define     MTFSM_CS_PATN_3                                 (AKS_PHY_TOP_BASE + 0x233)
#define     MTFSM_CS_PATN_4                                 (AKS_PHY_TOP_BASE + 0x234)
#define     MTFSM_CS_PATN_5                                 (AKS_PHY_TOP_BASE + 0x235)
#define     MTFSM_CS_PATN_6                                 (AKS_PHY_TOP_BASE + 0x236)
#define     MTFSM_CS_PATN_7                                 (AKS_PHY_TOP_BASE + 0x237)
#define     MTFSM_CS_PATN_8                                 (AKS_PHY_TOP_BASE + 0x238)
#define     MTFSM_CS_PATN_9                                 (AKS_PHY_TOP_BASE + 0x239)
#define     MTFSM_CS_PATN_10                                (AKS_PHY_TOP_BASE + 0x23a)
#define     MTFSM_CS_PATN_11                                (AKS_PHY_TOP_BASE + 0x23b)
#define     MTFSM_CS_PATN_12                                (AKS_PHY_TOP_BASE + 0x23c)
#define     MTFSM_CS_PATN_13                                (AKS_PHY_TOP_BASE + 0x23d)
#define     MTFSM_CS_PATN_14                                (AKS_PHY_TOP_BASE + 0x23e)
#define     MTFSM_CS_PATN_15                                (AKS_PHY_TOP_BASE + 0x23f)
// MTFSM  Reg  end

/* ---------------------------- aks_ddrphy_top_pstate_slv ------------------------------*/

#define      RATIO_CFG(p)                                 (AKS_PHY_TOP_BASE +  PSTATE_BASE(p)  + 0x0)
#define      TOP_DDR_CFG(p)                               (AKS_PHY_TOP_BASE +  PSTATE_BASE(p)  + 0x1)
#define      TOP_PRE_CFG(p)                               (AKS_PHY_TOP_BASE +  PSTATE_BASE(p)  + 0x2)
#define      TOP_POST_CFG(p)                              (AKS_PHY_TOP_BASE +  PSTATE_BASE(p)  + 0x3)
#define      FPSTATE_FREQ_INFO(p)                         (AKS_PHY_TOP_BASE +  PSTATE_BASE(p)  + 0x4)
#define      PLL_TXMODE_CONFIG(p)                         (AKS_PHY_TOP_BASE +  PSTATE_BASE(p)  + 0x5)
#define      PLL_PSTATE_CONFIG(p)                         (AKS_PHY_TOP_BASE +  PSTATE_BASE(p)  + 0x6)
#define      PLL_CP_CONFIG(p)                             (AKS_PHY_TOP_BASE +  PSTATE_BASE(p)  + 0x8)
#define      DL_TYPE_AND_REQ(p)                           (AKS_PHY_TOP_BASE +  PSTATE_BASE(p)  + 0x9)
#define      PSTATE_ZQ_CAL_CTRL_CFG(p)                    (AKS_PHY_TOP_BASE +  PSTATE_BASE(p)  + 0xa)
#define      MTFSM_TIMINGSET_0(p)                         (AKS_PHY_TOP_BASE +  PSTATE_BASE(p)  + 0x280)
#define      MTFSM_TIMINGSET_1(p)                         (AKS_PHY_TOP_BASE +  PSTATE_BASE(p)  + 0x281)
#define      MTFSM_TIMINGSET_2(p)                         (AKS_PHY_TOP_BASE +  PSTATE_BASE(p)  + 0x282)
#define      MTFSM_TIMINGSET_3(p)                         (AKS_PHY_TOP_BASE +  PSTATE_BASE(p)  + 0x283)
#define      MTFSM_TIMINGSET_4(p)                         (AKS_PHY_TOP_BASE +  PSTATE_BASE(p)  + 0x284)
#define      MTFSM_TIMINGSET_5(p)                         (AKS_PHY_TOP_BASE +  PSTATE_BASE(p)  + 0x285)
#define      MTFSM_TIMINGSET_6(p)                         (AKS_PHY_TOP_BASE +  PSTATE_BASE(p)  + 0x286)
#define      MTFSM_TIMINGSET_7(p)                         (AKS_PHY_TOP_BASE +  PSTATE_BASE(p)  + 0x287)
#define      MTFSM_TIMINGSET_8(p)                         (AKS_PHY_TOP_BASE +  PSTATE_BASE(p)  + 0x288)
#define      MTFSM_TIMINGSET_9(p)                         (AKS_PHY_TOP_BASE +  PSTATE_BASE(p)  + 0x289)
#define      MTFSM_TIMINGSET_10(p)                        (AKS_PHY_TOP_BASE +  PSTATE_BASE(p)  + 0x28a)
#define      MTFSM_TIMINGSET_11(p)                        (AKS_PHY_TOP_BASE +  PSTATE_BASE(p)  + 0x28b)
#define      MTFSM_TIMINGSET_12(p)                        (AKS_PHY_TOP_BASE +  PSTATE_BASE(p)  + 0x28c)
#define      MTFSM_TIMINGSET_13(p)                        (AKS_PHY_TOP_BASE +  PSTATE_BASE(p)  + 0x28d)
#define      MTFSM_TIMINGSET_14(p)                        (AKS_PHY_TOP_BASE +  PSTATE_BASE(p)  + 0x28e)
#define      MTFSM_TIMINGSET_15(p)                        (AKS_PHY_TOP_BASE +  PSTATE_BASE(p)  + 0x28f)
#define      MTFSM_TIMINGSET_16(p)                        (AKS_PHY_TOP_BASE +  PSTATE_BASE(p)  + 0x290)
#define      MTFSM_TIMINGSET_17(p)                        (AKS_PHY_TOP_BASE +  PSTATE_BASE(p)  + 0x291)
#define      MTFSM_2N_CFG(p)                              (AKS_PHY_TOP_BASE +  PSTATE_BASE(p)  + 0x2ce)

/* ---------------------------- aks_ddrphy_mcu_slv ------------------------------*/

#define      RCORE_CTRL                                     (MCUCSR_BASE   + 0x0)
#define      RCORE_STA                                      (MCUCSR_BASE   + 0x2)
#define      PCU_STA                                        (MCUCSR_BASE   + 0x3)
#define      MESSAGE_FLAG                                   (MCUCSR_BASE   + 0x4)
#define      MESSAGE_ADDR                                   (MCUCSR_BASE   + 0x5)
#define      MESSAGE_CODE                                   (MCUCSR_BASE   + 0x6)
#define      MCU_FULL_SPEED                                 (MCUCSR_BASE   + 0x10)
#define      RCORE_SRAM_CTRL                                (MCUCSR_BASE   + 0x11)


/* ---------------------------- aks_ddrphy_db_regs_pstate   N=0,1,2,......9; P=0,1,2,3;R=0,1,2,3 ------------------------------*/

#define      DQ_TX_DLY_0(n, p, r)                          (DB_BASE(n) + PSTATE_BASE(p) + 0x200 * r + 0x0)
#define      DQ_RX_DLY_0(n, p, r)                          (DB_BASE(n) + PSTATE_BASE(p) + 0x200 * r + 0x1)
#define      DQS_TX_DLY_0(n, p, r)                         (DB_BASE(n) + PSTATE_BASE(p) + 0x200 * r + 0x12)
#define      DQS_RXDCUP_DLY_0(n, p, r)                     (DB_BASE(n) + PSTATE_BASE(p) + 0x200 * r + 0x13)
#define      DQS_RXEN_DLY_0(n, p, r)                       (DB_BASE(n) + PSTATE_BASE(p) + 0x200 * r + 0x14)
#define      DB_CONFIG(n, p, r)                            (DB_BASE(n) + PSTATE_BASE(p) + 0x200 * r + 0x19)

#define      DB_SINGLE_ENDED_CONFIG(n, p, r)               (DB_BASE(n) + PSTATE_BASE(p) + 0x200 * r + 0x1d)

#define      RXVREF_CFG_DQ0(n, p, r)                       (DB_BASE(n) + PSTATE_BASE(p) + 0x200 * r + 0x1f)

/* ---------------------------- aks_ddrphy_db_regs_common   N=0,1,2,......9  ------------------------------*/

#define      DB_TRN_MODE(n)                                 (DB_BASE(n) + 0x00)
#define      DB_DDL_CFG(n)                                  (DB_BASE(n) + 0x01)
#define      DB_CLK_GATE_CFG(n)                             (DB_BASE(n) + 0x02)
#define      DB_RST_CFG(n)                                  (DB_BASE(n) + 0x03)
#define      CLK_T_C_FLAG(n)                                (DB_BASE(n) + 0x04)
#define      DB_LANE_DIS(n)                                 (DB_BASE(n) + 0x05)
#define      SNOOP_CTRL(n)                                  (DB_BASE(n) + 0x08)
#define      PGU_CTRL(n, l)                                 (DB_BASE(n) + 0x10 + l)
#define      PGU_FIX_PATN_SET(n, l)                         (DB_BASE(n) + 0x20 + l)
#define      PGU_PRBS_SEED_SET(n, l)                        (DB_BASE(n) + 0x30 + l)
#define      REMAP_LNDQ_SEL(n, l)                           (DB_BASE(n) + 0x40 + l)
#define      REMAP_LN0DQ_SEL(n)                             (DB_BASE(n) + 0x40)
#define      REMAP_LN1DQ_SEL(n)                             (DB_BASE(n) + 0x41)
#define      REMAP_LN2DQ_SEL(n)                             (DB_BASE(n) + 0x42)
#define      REMAP_LN3DQ_SEL(n)                             (DB_BASE(n) + 0x43)
#define      REMAP_LN4DQ_SEL(n)                             (DB_BASE(n) + 0x44)
#define      REMAP_LN5DQ_SEL(n)                             (DB_BASE(n) + 0x45)
#define      REMAP_LN6DQ_SEL(n)                             (DB_BASE(n) + 0x46)
#define      REMAP_LN7DQ_SEL(n)                             (DB_BASE(n) + 0x47)
#define      RXDAT_TST_0(n)                                 (DB_BASE(n) + 0x50)
#define      RXDAT_TST_1(n)                                 (DB_BASE(n) + 0x51)
#define      RXDAT_TST_2(n)                                 (DB_BASE(n) + 0x52)
#define      RXDAT_TST_3(n)                                 (DB_BASE(n) + 0x53)
#define      RETRAINING_RGATE_PATTERN(n)                    (DB_BASE(n) + 0x56)
#define      RXCLK_SEARCH_CFG(n)                            (DB_BASE(n) + 0x57)
#define      REPLICA_RD_DQS_MEASURE(n)                      (DB_BASE(n) + 0x58)
#define      REPLICA_RD_DQ_MEASURE(n)                       (DB_BASE(n) + 0x59)
#define      REPLICA_MEAS_INI_START(n)                      (DB_BASE(n) + 0x5a)
#define      OSC_RUN_CK_NUM(n)                              (DB_BASE(n) + 0x5b)
#define      DB_RSV_CFG_0(n)                                (DB_BASE(n) + 0x60)
#define      DB_RSV_CFG_1(n)                                (DB_BASE(n) + 0x61)
#define      DB_DDL_TEST_CFG(n)                             (DB_BASE(n) + 0x64)
#define      DB_COMMON_DDL_TEST_CNT(n)                      (DB_BASE(n) + 0x65)
#define      REPLICA_ANA_CFG0(n)                            (DB_BASE(n) + 0x66)
#define      REPLICA_ANA_CFG1(n)                            (DB_BASE(n) + 0x67)
#define      REPLICA_ANA_CFG2(n)                            (DB_BASE(n) + 0x68)
#define      DQS_CTRL(n)                                    (DB_BASE(n) + 0x69)
#define      DFE_PO_FIX_UP_NUM(n)                           (DB_BASE(n) + 0x70)
#define      DFE_PATTERN_H0_TAP(n)                          (DB_BASE(n) + 0x71)
#define      DFE_PATTERN_BEN(n)                             (DB_BASE(n) + 0x72)
#define      DFE_ANA_RXSAV_PREAMP(n)                        (DB_BASE(n) + 0x73)
#define      DFE_ANA_RANGE_DAC(n)                           (DB_BASE(n) + 0x74)

#define      ECC_DBI_WDQS(n)                                (DB_BASE(n) + 0x79)


/* ---------------------------- aks_ddrphy_db_regs_dq   N=0,1,2,......9; L=0,1,2,3,4,5,6,7,8  ------------------------------*/

#define      DQ_DL_CFG(n,l)                                 (DQ_BASE(n, l) + 0x000)
#define      DQ_DL_FIRW_INF(n,l)                            (DQ_BASE(n, l) + 0x001)
#define      DQ_DL_1UIC(n,l)                                (DQ_BASE(n, l) + 0x002)
#define      DQ_DL_CAL_INFO(n,l)                            (DQ_BASE(n, l) + 0x003)
#define      DQ_RCLKT_DL_CFG(n,l)                           (DQ_BASE(n, l) + 0x004)
#define      DQ_RCLKT_DL_FIRW_INF(n,l)                      (DQ_BASE(n, l) + 0x005)
#define      DQ_RCLKT_DL_1UIC(n,l)                          (DQ_BASE(n, l) + 0x006)
#define      DQ_RCLKT_DL_CAL_INFO(n,l)                      (DQ_BASE(n, l) + 0x007)
#define      DQ_RCLKC_DL_CFG(n,l)                           (DQ_BASE(n, l) + 0x008)
#define      DQ_RCLKC_DL_FIRW_INF(n,l)                      (DQ_BASE(n, l) + 0x009)
#define      DQ_RCLKC_DL_1UIC(n,l)                          (DQ_BASE(n, l) + 0x00a)
#define      DQ_RCLKC_DL_CAL_INFO(n,l)                      (DQ_BASE(n, l) + 0x00b)
#define      DQ_TTU_CTRL(n,l)                               (DQ_BASE(n, l) + 0x010)
#define      DQ_TTU_GTH(n,l)                                (DQ_BASE(n, l) + 0x011)
#define      DQ_TTU_ETH(n,l)                                (DQ_BASE(n, l) + 0x012)
#define      DQ_TTU_TRNCODE(n,l)                            (DQ_BASE(n, l) + 0x013)
#define      DQ_TTU_DICH_CTRL(n,l)                          (DQ_BASE(n, l) + 0x014)
#define      DQ_TTU_STA1(n,l)                               (DQ_BASE(n, l) + 0x015)
#define      DQ_TTU_STA2(n,l)                               (DQ_BASE(n, l) + 0X016)
#define      DQ_DCU_CTRL(n,l)                               (DQ_BASE(n, l) + 0x020)
#define      DQ_DCU_FIX_PATN_SET(n,l)                       (DQ_BASE(n, l) + 0x021)
#define      DQ_DCU_PRBS_SEED_SET(n,l)                      (DQ_BASE(n, l) + 0x022)
#define      DQ_DDL_TEST_CFG(n,l)                           (DQ_BASE(n, l) + 0x030)
#define      DQ_RCLKT_DDL_TEST_CFG(n,l)                     (DQ_BASE(n, l) + 0x031)
#define      DQ_RCLKC_DDL_TEST_CFG(n,l)                     (DQ_BASE(n, l) + 0x032)
#define      DQ_IO_TEST_CFG(n,l)                            (DQ_BASE(n, l) + 0x036)
#define      DQ_IO_TEST_STA(n,l)                            (DQ_BASE(n, l) + 0x037)
#define      DQ_PUD_CFG(n,l)                                (DQ_BASE(n, l) + 0x040)
#define      DQ_SEL_CFG(n,l)                                (DQ_BASE(n, l) + 0x041)
#define      DQ_RXDFEIDAC_CFG(n,l)                          (DQ_BASE(n, l) + 0x043)
#define      DQ_RXSAVDAC_CFG(n,l)                           (DQ_BASE(n, l) + 0x044)
#define      DQ_RXVREF_CFG(n,l)                             (DQ_BASE(n, l) + 0x045)
#define      DQ_RAC_CFG(n,l)                                (DQ_BASE(n, l) + 0x046)
#define      DQ_CCVT_CFG(n,l)                               (DQ_BASE(n, l) + 0x047)
#define      DQ_RXBIAS_CFG(n,l)                             (DQ_BASE(n, l) + 0x048)
#define      DQ_DTVR_CFG(n,l)                               (DQ_BASE(n, l) + 0x049)
#define      DQ_TXZQCAL_CFG(n,l)                            (DQ_BASE(n, l) + 0x04a)
#define      DQ_FORCE_ODT(n,l)                              (DQ_BASE(n, l) + 0x04b)
#define      DQ_TXFIFO_CFG(n,l)                             (DQ_BASE(n, l) + 0x04c)
#define      DQ_RXFIFOT_CFG(n,l)                            (DQ_BASE(n, l) + 0x04d)
#define      DQ_RXFIFOC_CFG(n,l)                            (DQ_BASE(n, l) + 0x04e)
#define      DQ_STROB_CFG(n,l)                              (DQ_BASE(n, l) + 0x04f)
#define      DQ_RXFIFO_RPTR(n,l)                            (DQ_BASE(n, l) + 0x050)
#define      DQ_PAD_CFG(n,l)                                (DQ_BASE(n, l) + 0x051)
#define      DQ_TEST_PIN_SEL(n,l)                           (DQ_BASE(n, l) + 0x052)
#define      DQ_DFE_REQ(n,l)                                (DQ_BASE(n, l) + 0x060)
#define      DQ_DFE_STAT(n,l)                               (DQ_BASE(n, l) + 0x061)
#define      DQ_DFE_DATA_ERR(n,l)                           (DQ_BASE(n, l) + 0x062)
#define      DQ_DFE_RXDFEIDAC_TAP(n,l)                      (DQ_BASE(n, l) + 0x063)
#define      DQ_DFE_PREA_VGA_OFFSET(n,l)                    (DQ_BASE(n, l) + 0x064)


/* ---------------------------- aks_ddrphy_db_regs_dqs   N=0,1,2,......9; L=0,1,2  ------------------------------*/

#define      DQS_DL_CFG(n,l)                                (DQS_BASE(n, l) + 0x000)
#define      DQS_DL_CAL_CN(n,l)                             (DQS_BASE(n, l) + 0x001)
#define      DQS_DL_1UIC(n,l)                               (DQS_BASE(n, l) + 0x002)
#define      DQS_DL_CAL_INFO(n,l)                           (DQS_BASE(n, l) + 0x003)
#define      DQS_RCLKT_DL_CFG(n,l)                          (DQS_BASE(n, l) + 0x004)
#define      DQS_RCLKT_DL_CAL_CN(n,l)                       (DQS_BASE(n, l) + 0x005)
#define      DQS_RCLKT_DL_1UIC(n,l)                         (DQS_BASE(n, l) + 0x006)
#define      DQS_RCLKT_DL_CAL_INFO(n,l)                     (DQS_BASE(n, l) + 0x007)
#define      DQS_RCLKC_DL_CFG(n,l)                          (DQS_BASE(n, l) + 0x008)
#define      DQS_RCLKC_DL_CAL_CN(n,l)                       (DQS_BASE(n, l) + 0x009)
#define      DQS_RCLKC_DL_1UIC(n,l)                         (DQS_BASE(n, l) + 0x00a)
#define      DQS_RCLKC_DL_CAL_INFO(n,l)                     (DQS_BASE(n, l) + 0x00b)
#define      DQS_TTU_CTRL(n,l)                              (DQS_BASE(n, l) + 0x010)
#define      DQS_TTU_GTH(n,l)                               (DQS_BASE(n, l) + 0x011)
#define      DQS_TTU_ETH(n,l)                               (DQS_BASE(n, l) + 0x012)
#define      DQS_TTU_TRNCODE(n,l)                           (DQS_BASE(n, l) + 0x013)
#define      DQS_TTU_DICH_CTRL(n,l)                         (DQS_BASE(n, l) + 0x014)
#define      DQS_TTU_STA1(n,l)                              (DQS_BASE(n, l) + 0x015)
#define      DQS_TTU_STA2(n,l)                              (DQS_BASE(n, l) + 0X016)
#define      DQS_DCU_CTRL(n,l)                              (DQS_BASE(n, l) + 0x020)
#define      DQS_DCU_FIX_PATN_SET(n,l)                      (DQS_BASE(n, l) + 0x021)
#define      DQS_DCU_PRBS_SEED_SET(n,l)                     (DQS_BASE(n, l) + 0x022)
#define      DQS_DCU_WRLEV_SEL(n,l)                         (DQS_BASE(n, l) + 0x023)
#define      DQS_DDL_TEST_CFG(n,l)                          (DQS_BASE(n, l) + 0x030)
#define      DQS_RCLKT_DDL_TEST_CFG(n,l)                    (DQS_BASE(n, l) + 0x031)
#define      DQS_RCLKC_DDL_TEST_CFG(n,l)                    (DQS_BASE(n, l) + 0x032)
#define      DQS_IO_TEST_CFG(n,l)                           (DQS_BASE(n, l) + 0x036)
#define      DQS_IO_TEST_STA(n,l)                           (DQS_BASE(n, l) + 0x037)
#define      DQS_TOT_PUD_CFG(n,l)                           (DQS_BASE(n, l) + 0x040)
#define      DQS_TVDR_MODE_CFG(n,l)                         (DQS_BASE(n, l) + 0x041)
#define      DQS_RX_DAC_CFG(n,l)                            (DQS_BASE(n, l) + 0x042)
#define      DQS_RXRE_CFG(n,l)                              (DQS_BASE(n, l) + 0x043)
#define      DQS_RCAV_CFG(n,l)                              (DQS_BASE(n, l) + 0x044)
#define      DQS_RX_COMPCAL_OUT(n,l)                        (DQS_BASE(n, l) + 0x049)
#define      DQS_TXZQCAL_CFG(n,l)                           (DQS_BASE(n, l) + 0x04a)
#define      DQS_FORCE_ODT(n,l)                             (DQS_BASE(n, l) + 0x04b)
#define      DQS_TXFIFO_CFG(n,l)                            (DQS_BASE(n, l) + 0x04c)
#define      DQS_RXFIFOT_CFG(n,l)                           (DQS_BASE(n, l) + 0x04d)
#define      DQS_RXFIFOC_CFG(n,l)                           (DQS_BASE(n, l) + 0x04e)
#define      DQS_STROB_CFG(n,l)                             (DQS_BASE(n, l) + 0x04f)
#define      DQS_RXFIFO_RPTR(n,l)                           (DQS_BASE(n, l) + 0x050)
#define      DQS_PAD_CFG(n,l)                               (DQS_BASE(n, l) + 0x051)
#define      DQS_TEST_PIN_SEL(n,l)                          (DQS_BASE(n, l) + 0x052)
#define      DQS_RXCLK_SAMP_EN(n,l)                         (DQS_BASE(n, l) + 0x053)
#define      DQS_WCK_CFG(n,l)                               (DQS_BASE(n, l) + 0x054)





/* ---------------------------- aks_ddrphy_ca_regs_pstate   N=0,1;  P=0,1,2,3;  R=0,1,2,3 ------------------------------*/
#define      CA_TX_DLY_0_1(n,p,r)                             (CA_BASE(n) + PSTATE_BASE(p) + 0x200 * r + 0x00)

#define      CA_HSEN_CFG(n, p, r)                             (CA_BASE(n) + PSTATE_BASE(p) + 0x200 * r + 0x15)


/* ---------------------------- aks_ddrphy_ca_regs_common   N=0,1 ------------------------------*/
#define      CA_TRN_MODE(n)                                 (CA_BASE(n) +  0x000)
#define      CA_CLK_GATE_CFG(n)                             (CA_BASE(n)  + 0x002)
#define      CA_RST_CFG(n)                                  (CA_BASE(n)  + 0x003)
#define      REMAP_LNCA_SEL(n, l)                           (CA_BASE(n) +  0x010 + l)
#define      REMAP_LN0CA_SEL(n)                             (CA_BASE(n) +  0x010)
#define      REMAP_LN1CA_SEL(n)                             (CA_BASE(n) +  0x011)
#define      REMAP_LN2CA_SEL(n)                             (CA_BASE(n) +  0x012)
#define      REMAP_LN3CA_SEL(n)                             (CA_BASE(n) +  0x013)
#define      REMAP_LN4CA_SEL(n)                             (CA_BASE(n) +  0x014)
#define      REMAP_LN5CA_SEL(n)                             (CA_BASE(n) +  0x015)
#define      REMAP_LN6CA_SEL(n)                             (CA_BASE(n) +  0x016)
#define      REMAP_LN7CA_SEL(n)                             (CA_BASE(n) +  0x017)
#define      REMAP_LN8CA_SEL(n)                             (CA_BASE(n) +  0x018)
#define      REMAP_LN9CA_SEL(n)                             (CA_BASE(n) +  0x019)
#define      REMAP_LN10CA_SEL(n)                            (CA_BASE(n) +  0x01a)
#define      REMAP_LN11CA_SEL(n)                            (CA_BASE(n) +  0x01b)
#define      REMAP_LN12CA_SEL(n)                            (CA_BASE(n) +  0x01c)
#define      REMAP_LN13CA_SEL(n)                            (CA_BASE(n) +  0x01d)
#define      CA_CK_CTRL(n)                                  (CA_BASE(n)  + 0x020)
#define      CA_ADDR_CTRL(n)                                (CA_BASE(n) +  0x021)
#define      CA_CKE_CTRL(n)                                 (CA_BASE(n) +  0x022)
/* CSR function: low 8 bits indicate the initial value of CS signal from DFI. When bypass mode of CA_CS_IO_TEST_CFG is disabled (oe & ie are both configured to 0), the CS signal comes from these 8 bits
   bit[11:8] indicate the enable switch of 4 CS signals */
#define      CA_CS_CTRL(n)                                  (CA_BASE(n) +  0x023)
#define      CA_ODT_CTRL(n)                                 (CA_BASE(n) +  0x024)
#define      CA_CID_CTRL(n)                                 (CA_BASE(n) +  0x025)
#define      CA_BBAP_CTRL(n)                                (CA_BASE(n) +  0x026)
#define      CA_CS_BC(n)                                    (CA_BASE(n) +  0x028)
#define      CA_RSV_CFG_0(n)                                (CA_BASE(n) +  0x030)
#define      CA_RSV_CFG_1(n)                                (CA_BASE(n) +  0x031)
#define      CA_DDL_TEST_CFG(n)                             (CA_BASE(n) +  0x034)
#define      CA_COMMON_DDL_TEST_CNT(n)                      (CA_BASE(n) +  0x035)



/* ---------------------------- aks_ddrphy_ca_regs_out   N=0,1;L=0,1,2,3,4,5,6,7,8……38 ------------------------------*/
#define      CA_OUT_DL_CFG(n,l)                             (CA_OUT_BASE(n, l) + 0x000)
#define      CA_OUT_DL_CAL_CN(n,l)                          (CA_OUT_BASE(n, l) + 0x001)
#define      CA_OUT_DL_1UIC(n,l)                            (CA_OUT_BASE(n, l) + 0x002)
#define      CA_OUT_DL_CAL_INFO(n,l)                        (CA_OUT_BASE(n, l) + 0x003)
#define      CA_OUT_TTU_CTRL(n,l)                           (CA_OUT_BASE(n, l) + 0x010)
#define      CA_OUT_TTU_GTH(n,l)                            (CA_OUT_BASE(n, l) + 0x011)
#define      CA_OUT_TTU_ETH(n,l)                            (CA_OUT_BASE(n, l) + 0x012)
#define      CA_OUT_TTU_TRNCODE(n,l)                        (CA_OUT_BASE(n, l) + 0x013)
#define      CA_OUT_TTU_DICH_CTRL(n,l)                      (CA_OUT_BASE(n, l) + 0x014)
#define      CA_OUT_TTU_STA1(n,l)                           (CA_OUT_BASE(n, l) + 0x015)
#define      CA_OUT_TTU_STA2(n,l)                           (CA_OUT_BASE(n, l) + 0X016)
#define      CA_OUT_DDL_TEST_CFG(n,l)                       (CA_OUT_BASE(n, l) + 0x020)
#define      CA_OUT_DDL_TEST_CNT(n,l)                       (CA_OUT_BASE(n, l) + 0x021)
#define      CA_OUT_IO_TEST_CFG(n,l)                        (CA_OUT_BASE(n, l) + 0x022)
#define      CA_OUT_SCLICE_PRBS_CFG(n,l)                    (CA_OUT_BASE(n, l) + 0x023)
#define      CA_OUT_SCLICE_PRBS_ERR_CNT(n,l)                (CA_OUT_BASE(n, l) + 0x024)
#define      CA_OUT_SCLICE_PRBS_SYNC(n,l)                   (CA_OUT_BASE(n, l) + 0x025)
#define      CA_OUT_PUD_CFG(n,l)                            (CA_OUT_BASE(n, l) + 0x030)
#define      CA_OUT_VRADT_CFG(n,l)                          (CA_OUT_BASE(n, l) + 0x031)
#define      CA_OUT_TXZQCAL_CFG(n,l)                        (CA_OUT_BASE(n, l) + 0x032)
#define      CA_OUT_FORCE_ODT(n,l)                          (CA_OUT_BASE(n, l) + 0x033)
#define      CA_OUT_OUTC_CFG(n,l)                           (CA_OUT_BASE(n, l) + 0x034)
#define      CA_OUT_TXFIFO_CFG(n,l)                         (CA_OUT_BASE(n, l) + 0x035)
#define      CA_OUT_RES0_CFG(n,l)                           (CA_OUT_BASE(n, l) + 0x036)
#define      CA_OUT_RES1_CFG(n,l)                           (CA_OUT_BASE(n, l) + 0x037)
#define      CA_OUT_TEST_PIN_SEL(n,l)                       (CA_OUT_BASE(n, l) + 0x038)
#define      CA_OUT_PAD_CFG(n,l)                            (CA_OUT_BASE(n, l) + 0x039)


/* ---------------------------- aks_ddrphy_ca_regs_ck   N=0,1; L=0,1,2,3 ------------------------------*/
#define      CA_CK_DL_CFG(n,l)                              (CA_CK_BASE(n, l) + 0x000)
#define      CA_CK_DL_CAL_CN(n,l)                           (CA_CK_BASE(n, l) + 0x001)
#define      CA_CK_DL_1UIC(n,l)                             (CA_CK_BASE(n, l) + 0x002)
#define      CA_CK_DL_CAL_INFO(n,l)                         (CA_CK_BASE(n, l) + 0x003)
#define      CA_CK_DDL_TEST_CFG(n,l)                        (CA_CK_BASE(n, l) + 0x020)
#define      CA_CK_DDL_TEST_CNT(n,l)                        (CA_CK_BASE(n, l) + 0x021)
#define      CA_CK_IO_TEST_CFG(n,l)                         (CA_CK_BASE(n, l) + 0x022)
#define      CA_CK_IO_TEST_STA(n,l)                         (CA_CK_BASE(n, l) + 0x023)
#define      CA_CK_TOT_PUD_CFG(n,l)                         (CA_CK_BASE(n, l) + 0x030)
#define      CA_CK_TVDR_MODE_CFG(n,l)                       (CA_CK_BASE(n, l) + 0x031)
#define      CA_CK_RX_DAC_CFG(n,l)                          (CA_CK_BASE(n, l) + 0x032)
#define      CA_CK_RXRE_CFG(n,l)                            (CA_CK_BASE(n, l) + 0x033)
#define      CA_CK_RCAV_CFG(n,l)                            (CA_CK_BASE(n, l) + 0x034)
#define      CA_CK_RX_COMPCAL_OUT(n,l)                      (CA_CK_BASE(n, l) + 0x035)
#define      CA_CK_TXZQCAL_CFG(n,l)                         (CA_CK_BASE(n, l) + 0x036)
#define      CA_CK_FORCE_ODT(n,l)                           (CA_CK_BASE(n, l) + 0x037)
#define      CA_CK_TXFIFO_CFG(n,l)                          (CA_CK_BASE(n, l) + 0x038)
#define      CA_CK_DIGITAL_STROBE(n,l)                      (CA_CK_BASE(n, l) + 0x039)
#define      CA_CK_RES0_CFG(n,l)                            (CA_CK_BASE(n, l) + 0x03a)
#define      CA_CK_RES1_CFG(n,l)                            (CA_CK_BASE(n, l) + 0x03b)
#define      CA_CK_TEST_PIN_SEL(n,l)                        (CA_CK_BASE(n, l) + 0x03c)
#define      CA_CK_PAD_CFG(n,l)                             (CA_CK_BASE(n, l) + 0x03d)
